### ISSUE TITLE
真机首次或者高频点击按钮运行报错

### ISSUE THREAD

**Issue by ghost** [rogchap/libfoo#2]
模拟器上使用一起正常 但是真机第一次加载或者频繁点击就会报错

signal 16 received on thread with no signal stack
fatal error: non-Go code disabled sigaltstack

runtime stack:
runtime: unexpected return pc for runtime.sigtramp called from 0x1dca4ed48
stack: frame={sp:0x130040810, fp:0x1300408e0} stack=[0x1300386f0,0x130040af0)
0x0000000130040710:  0x0000000130040768  0x0000000000000000 
0x0000000130040720:  0x0000000000000000  0x0000000000000000 
0x0000000130040730:  0x0000000000000000  0x0000000000000000 
0x0000000130040740:  0x0000000000000000  0x0000000000000000 
0x0000000130040750:  0x0000000000000004  0x00000001300407d8 
0x0000000130040760:  0x00000001045268ec <runtime.sigtrampgo+0x000000000000001c>  0x0000000100000010 
0x0000000130040770:  0x0000000104596780  0x0000000130040798 
0x0000000130040780:  0x0000000000000000  0x0000000000000000 
0x0000000130040790:  0x0000000000000000  0x0000000000000000 
0x00000001300407a0:  0x0000000000000000  0x0000000000000000 
0x00000001300407b0:  0x0000000000000000  0x0000000000000000 
0x00000001300407c0:  0x00000001300021a0  0x0000000130040910 
0x00000001300407d0:  0x0000000130040978  0x0000000130040808 
0x00000001300407e0:  0x0000000104525f84 <runtime.sigtramp+0x0000000000000074>  0x0000000000000010 
0x00000001300407f0:  0x0000000130040910  0x0000000130040978 
0x0000000130040800:  0x0000000000000000  0x0000000130040900 
0x0000000130040810: <0x00000001dca4ed48  0x0000000000000010 
0x0000000130040820:  0x0000000130040910  0x0000000130040978 
0x0000000130040830:  0x83a32c02d344d65b  0x0000000130040978 
0x0000000130040840:  0x00000001f4231000  0x00000001045c4f14 
0x0000000130040850:  0x0000000000000000  0x0000000000000000 
0x0000000130040860:  0x0000000000000000  0x0000000104594cc0 
0x0000000130040870:  0x00000001045430e0  0x00000001300021a0 
0x0000000130040880:  0x0000000130040808  0x0000000000000000 
0x0000000130040890:  0x0000000000000000  0x0000000000000000 
0x00000001300408a0:  0x0000000000000000  0x0000000000000000 
0x00000001300408b0:  0x0000000000000000  0x0000000000000000 
0x00000001300408c0:  0x0000000000000000  0x0000000000000000 
0x00000001300408d0:  0x0000000000000000  0x0000000000000000 
0x00000001300408e0: >0x00000001045c4f14  0x0000000000000003 
0x00000001300408f0:  0x000000000000007d  0x0000000130040f58 
0x0000000130040900:  0x0000000130040d58  0x00000001044ff50c <runtime.init.5+0x000000000000002c> 
0x0000000130040910:  0x0000000000000010  0x0000000000000000 
0x0000000130040920:  0x0000000000000000  0x0000000104518ca0 <runtime.funcMaxSPDelta+0x0000000000000030> 
0x0000000130040930:  0x0000000000000000  0x0000000000000000 
0x0000000130040940:  0x0000000000000000  0x0000000000000000 
0x0000000130040950:  0x0000000000000000  0x0000000000000000 
0x0000000130040960:  0x0000000000000000  0x0000000000000000 
0x0000000130040970:  0x0000000000000000  0x0000000000000000 
0x0000000130040980:  0x0000000130040910  0x0000000000000000 
0x0000000130040990:  0x0000000000000000  0x0000000000000000 
0x00000001300409a0:  0x0000000000000330  0x00000001300409b0 
0x00000001300409b0:  0x000000010458be28  0x0000000092000007 
0x00000001300409c0:  0x000000010458be18  0x00000001045951c0 
0x00000001300409d0:  0x000000000001c7a0  0x000000010455b7e0 
runtime.throw({0x104530105?, 0x130044000?})
	/usr/local/go/src/runtime/panic.go:992 +0x50
runtime.noSignalStack(0x10)
	/usr/local/go/src/runtime/signal_unix.go:994 +0x60
runtime.adjustSignalStack(0x10, 0x104596780, 0x130040798)
	/usr/local/go/src/runtime/signal_unix.go:575 +0x24c
runtime.sigtrampgo(0x10, 0x130040910, 0x130040978)
	/usr/local/go/src/runtime/signal_unix.go:467 +0x174
runtime.sigtrampgo(0x10, 0x130040910, 0x130040978)
	<autogenerated>:1 +0x1c
runtime: unexpected return pc for runtime.sigtramp called from 0x1dca4ed48
stack: frame={sp:0x130040810, fp:0x1300408e0} stack=[0x1300386f0,0x130040af0)
0x0000000130040710:  0x0000000130040768  0x0000000000000000 
0x0000000130040720:  0x0000000000000000  0x0000000000000000 
0x0000000130040730:  0x0000000000000000  0x0000000000000000 
0x0000000130040740:  0x0000000000000000  0x0000000000000000 
0x0000000130040750:  0x0000000000000004  0x00000001300407d8 
0x0000000130040760:  0x00000001045268ec <runtime.sigtrampgo+0x000000000000001c>  0x0000000100000010 
0x0000000130040770:  0x0000000104596780  0x0000000130040798 
0x0000000130040780:  0x0000000000000000  0x0000000000000000 
0x0000000130040790:  0x0000000000000000  0x0000000000000000 
0x00000001300407a0:  0x0000000000000000  0x0000000000000000 
0x00000001300407b0:  0x0000000000000000  0x0000000000000000 
0x00000001300407c0:  0x00000001300021a0  0x0000000130040910 
0x00000001300407d0:  0x0000000130040978  0x0000000130040808 
0x00000001300407e0:  0x0000000104525f84 <runtime.sigtramp+0x0000000000000074>  0x0000000000000010 
0x00000001300407f0:  0x0000000130040910  0x0000000130040978 
0x0000000130040800:  0x0000000000000000  0x0000000130040900 
0x0000000130040810: <0x00000001dca4ed48  0x0000000000000010 
0x0000000130040820:  0x0000000130040910  0x0000000130040978 
0x0000000130040830:  0x83a32c02d344d65b  0x0000000130040978 
0x0000000130040840:  0x00000001f4231000  0x00000001045c4f14 
0x0000000130040850:  0x0000000000000000  0x0000000000000000 
0x0000000130040860:  0x0000000000000000  0x0000000104594cc0 
0x0000000130040870:  0x00000001045430e0  0x00000001300021a0 
0x0000000130040880:  0x0000000130040808  0x0000000000000000 
0x0000000130040890:  0x0000000000000000  0x0000000000000000 
0x00000001300408a0:  0x0000000000000000  0x0000000000000000 
0x00000001300408b0:  0x0000000000000000  0x0000000000000000 
0x00000001300408c0:  0x0000000000000000  0x0000000000000000 
0x00000001300408d0:  0x0000000000000000  0x0000000000000000 
0x00000001300408e0: >0x00000001045c4f14  0x0000000000000003 
0x00000001300408f0:  0x000000000000007d  0x0000000130040f58 
0x0000000130040900:  0x0000000130040d58  0x00000001044ff50c <runtime.init.5+0x000000000000002c> 
0x0000000130040910:  0x0000000000000010  0x0000000000000000 
0x0000000130040920:  0x0000000000000000  0x0000000104518ca0 <runtime.funcMaxSPDelta+0x0000000000000030> 
0x0000000130040930:  0x0000000000000000  0x0000000000000000 
0x0000000130040940:  0x0000000000000000  0x0000000000000000 
0x0000000130040950:  0x0000000000000000  0x0000000000000000 
0x0000000130040960:  0x0000000000000000  0x0000000000000000 
0x0000000130040970:  0x0000000000000000  0x0000000000000000 
0x0000000130040980:  0x0000000130040910  0x0000000000000000 
0x0000000130040990:  0x0000000000000000  0x0000000000000000 
0x00000001300409a0:  0x0000000000000330  0x00000001300409b0 
0x00000001300409b0:  0x000000010458be28  0x0000000092000007 
0x00000001300409c0:  0x000000010458be18  0x00000001045951c0 
0x00000001300409d0:  0x000000000001c7a0  0x000000010455b7e0 
runtime.sigtramp()
	/usr/local/go/src/runtime/sys_darwin_arm64.s:243 +0x74

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x13005bfe0 sp=0x13005bfe0 pc=0x104525074

goroutine 1 [running, locked to thread]:
	goroutine running on other thread; stack unavailable
dyld4 config: DYLD_LIBRARY_PATH=/usr/lib/system/introspection DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib

**Comment by ghost** [comment]
lucky,change GOOS=darwin to GOOS=ios can fix this problem
